var annotated_dup =
[
    [ "AZX_CJSON_TAG", "struct_a_z_x___c_j_s_o_n___t_a_g.html", "struct_a_z_x___c_j_s_o_n___t_a_g" ],
    [ "AZX_EASY_AT_ATCOMMAND_TAG", "struct_a_z_x___e_a_s_y___a_t___a_t_c_o_m_m_a_n_d___t_a_g.html", "struct_a_z_x___e_a_s_y___a_t___a_t_c_o_m_m_a_n_d___t_a_g" ],
    [ "AZX_EASY_AT_HANDLES_TAG", "struct_a_z_x___e_a_s_y___a_t___h_a_n_d_l_e_s___t_a_g.html", "struct_a_z_x___e_a_s_y___a_t___h_a_n_d_l_e_s___t_a_g" ],
    [ "AZX_EASY_AT_MODULE_TAG", "struct_a_z_x___e_a_s_y___a_t___m_o_d_u_l_e___t_a_g.html", "struct_a_z_x___e_a_s_y___a_t___m_o_d_u_l_e___t_a_g" ],
    [ "AZX_FTP_BUFFER", "struct_a_z_x___f_t_p___b_u_f_f_e_r.html", null ],
    [ "AZX_FTP_BUFFER_TAG", "struct_a_z_x___f_t_p___b_u_f_f_e_r___t_a_g.html", "struct_a_z_x___f_t_p___b_u_f_f_e_r___t_a_g" ],
    [ "AZX_FTP_CALLBACK_OPTIONS_TAG", "struct_a_z_x___f_t_p___c_a_l_l_b_a_c_k___o_p_t_i_o_n_s___t_a_g.html", "struct_a_z_x___f_t_p___c_a_l_l_b_a_c_k___o_p_t_i_o_n_s___t_a_g" ],
    [ "AZX_FTP_FILE_INFO", "struct_a_z_x___f_t_p___f_i_l_e___i_n_f_o.html", null ],
    [ "AZX_FTP_FILE_INFO_TAG", "struct_a_z_x___f_t_p___f_i_l_e___i_n_f_o___t_a_g.html", "struct_a_z_x___f_t_p___f_i_l_e___i_n_f_o___t_a_g" ],
    [ "AZX_FTP_NET_BUF_TAG", "struct_a_z_x___f_t_p___n_e_t___b_u_f___t_a_g.html", null ],
    [ "AZX_FTP_OPTIONS_TAG", "struct_a_z_x___f_t_p___o_p_t_i_o_n_s___t_a_g.html", "struct_a_z_x___f_t_p___o_p_t_i_o_n_s___t_a_g" ],
    [ "AZX_FTP_XFER_TAG", "struct_a_z_x___f_t_p___x_f_e_r___t_a_g.html", "struct_a_z_x___f_t_p___x_f_e_r___t_a_g" ],
    [ "AZX_HTTP_HEADER", "struct_a_z_x___h_t_t_p___h_e_a_d_e_r.html", "struct_a_z_x___h_t_t_p___h_e_a_d_e_r" ],
    [ "AZX_HTTP_INFO", "struct_a_z_x___h_t_t_p___i_n_f_o.html", "struct_a_z_x___h_t_t_p___i_n_f_o" ],
    [ "AZX_HTTP_OPTIONS", "struct_a_z_x___h_t_t_p___o_p_t_i_o_n_s.html", "struct_a_z_x___h_t_t_p___o_p_t_i_o_n_s" ],
    [ "AZX_HTTP_SSL", "struct_a_z_x___h_t_t_p___s_s_l.html", "struct_a_z_x___h_t_t_p___s_s_l" ],
    [ "AZX_HTTP_URL", "struct_a_z_x___h_t_t_p___u_r_l.html", "struct_a_z_x___h_t_t_p___u_r_l" ],
    [ "azx_httpCallbackOptions", "structazx__http_callback_options.html", "structazx__http_callback_options" ],
    [ "AZX_HTTPS_OPTIONS", "struct_a_z_x___h_t_t_p_s___o_p_t_i_o_n_s.html", null ],
    [ "AZX_LOG_CFG_T", "struct_a_z_x___l_o_g___c_f_g___t.html", "struct_a_z_x___l_o_g___c_f_g___t" ],
    [ "AZX_TASKS_MESSAGE_T", "struct_a_z_x___t_a_s_k_s___m_e_s_s_a_g_e___t.html", "struct_a_z_x___t_a_s_k_s___m_e_s_s_a_g_e___t" ],
    [ "EASY_AT_HANDLES_TAG", "struct_e_a_s_y___a_t___h_a_n_d_l_e_s___t_a_g.html", null ],
    [ "EASY_AT_MODULE_TAG", "struct_e_a_s_y___a_t___m_o_d_u_l_e___t_a_g.html", null ],
    [ "FtpCallbackOptions", "struct_ftp_callback_options.html", null ],
    [ "sockaddr_storage", "structsockaddr__storage.html", "structsockaddr__storage" ]
];